version: '3.8'

services:
  # KHO CHỨA DỮ LIỆU (DATABASE)
  influxdb:
    image: influxdb:2.7
    container_name: vn30_influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345678 # Mật khẩu database
      - DOCKER_INFLUXDB_INIT_ORG=vnquant
      - DOCKER_INFLUXDB_INIT_BUCKET=market_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb_data:/var/lib/influxdb2

  # BẢNG ĐIỀU KHIỂN (DASHBOARD)
  grafana:
    image: grafana/grafana:latest
    container_name: vn30_grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

  # CON BOT SĂN DỮ LIỆU (AGENT)
  hunter:
    build: ./hunter
    container_name: vn30_hunter
    restart: always
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=vnquant
      - INFLUX_BUCKET=market_data
      - TARGET_STOCK=HPG
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
